### ISSUE TITLE
some wasm libs can not load

### ISSUE THREAD

**Issue by winyluo** [Creativeguru97/YouTube_tutorial#2]
NetworkError for: https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_packed_assets.data

**Comment by TimB25** [comment]
I think I have the same problem. I have cloned the repository and viewed the index.html file in the final mediapipe_hands hand_detection Play with API's folder. I have viewed it in chrome and get the folowing error: 

`hands_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    at abort (hands_solution_simd_wasm_bin.js:9:17640)
    at _abort (hands_solution_simd_wasm_bin.js:9:157706)
    at hands_solution_simd_wasm_bin.wasm:0x4d6d66
    at hands_solution_simd_wasm_bin.wasm:0x4d68d4
    at hands_solution_simd_wasm_bin.wasm:0x4d6f8e
    at hands_solution_simd_wasm_bin.wasm:0x1f26c
    at hands_solution_simd_wasm_bin.wasm:0x19cb6
    at ClassHandle.send (hands_solution_simd_wasm_bin.js:9:131923)
    at ra.i (hands.js:82:499)
    at ua (hands.js:14:299)`

The hand detection does not appear to work. The camera view does work. 
Full log: 


<details><summary>Details</summary>
<p>

Live reload enabled.
hands_solution_simd_wasm_bin.js:9 I0000 00:00:1716309940.921000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 3
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 I0000 00:00:1716309940.954000       1 gl_context.cc:359] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 W0000 00:00:1716309940.955000       1 gl_context.cc:1000] OpenGL error checking is disabled
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 E0000 00:00:1716309941.371000       1 calculator_graph.cc:848] UNKNOWN: CalculatorGraph::Run() failed in Run: 
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 Calculator::Open() for node "handlandmarktrackinggpu__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite. [type.googleapis.com/mediapipe.StatusList='\n\xe4\x01\x08\x02\x12\xdf\x01\x43\x61lculator::Open() for node \"handlandmarktrackinggpu__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator\" failed: Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite.']
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 === Source Location Trace: ===
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 third_party/mediapipe/util/resource_util_emscripten.cc:59
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 third_party/mediapipe/calculators/util/local_file_contents_calculator.cc:108
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 third_party/mediapipe/framework/calculator_node.cc:558
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 F0000 00:00:1716309941.372000       1 solutions_wasm.embind.cc:678] Check failed: graph_->WaitUntilIdle() is OK (UNKNOWN: CalculatorGraph::Run() failed in Run: 
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 Calculator::Open() for node "handlandmarktrackinggpu__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite. [type.googleapis.com/mediapipe.StatusList='\n\xe4\x01\x08\x02\x12\xdf\x01\x43\x61lculator::Open() for node \"handlandmarktrackinggpu__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator\" failed: Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite.']
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 === Source Location Trace: ===
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 third_party/mediapipe/util/resource_util_emscripten.cc:59
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 third_party/mediapipe/calculators/util/local_file_contents_calculator.cc:108
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 third_party/mediapipe/framework/calculator_node.cc:558
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 ) 
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 *** Check failure stack trace: ***
put_char @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 Aborted(native code called abort())
abort @ hands_solution_simd_wasm_bin.js:9
hands_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    at abort (hands_solution_simd_wasm_bin.js:9:17640)
    at _abort (hands_solution_simd_wasm_bin.js:9:157706)
    at hands_solution_simd_wasm_bin.wasm:0x4d6d66
    at hands_solution_simd_wasm_bin.wasm:0x4d68d4
    at hands_solution_simd_wasm_bin.wasm:0x4d6f8e
    at hands_solution_simd_wasm_bin.wasm:0x1f26c
    at hands_solution_simd_wasm_bin.wasm:0x19cb6
    at ClassHandle.send (hands_solution_simd_wasm_bin.js:9:131923)
    at ra.i (hands.js:82:499)
    at ua (hands.js:14:299)



</p>
</details>
